[project]
name = "seisbai_tools"
version = "1.0.0"
dependencies = [
    "msgspec",
    "ulid-py"
]

[build-system]
requires = [
    "setuptools", 
    "msgspec",
    "ulid-py"
]
build-backend = "setuptools.build_meta"